knp_gaufrette:
    adapters:
        attachments:
            local:
                directory: '%kernel.project_dir%/var/%oro_attachment.attachments_dir%'
        mediacache:
            local:
                directory: '%kernel.project_dir%/public/%oro_attachment.media_cache_dir%'
    filesystems:
        attachments:
            adapter:    attachments
            alias:      attachments_filesystem
        mediacache:
            adapter:    mediacache
            alias:      mediacache_filesystem
