services:
    Oro\Bundle\OrganizationBundle\Command\UpdateOrganizationCommand:
        public: false
        class: Oro\Bundle\OrganizationBundle\Command\UpdateOrganizationCommand
        tags:
            - { name: console.command }
