config:
    paths:
        'oro/select2-bu-tree-autocomplete-component': 'bundles/oroorganization/js/app/components/select2-bu-tree-autocomplete-component.js'
        'oroorganization/js/app/views/select2-bu-tree-autocomplete-view': 'bundles/oroorganization/js/app/views/select2-bu-tree-autocomplete-view.js'
        'oro/select2-parent-business-units-autocomplete-component': 'bundles/oroorganization/js/app/components/select2-parent-business-units-autocomplete-component.js'
