parameters:
    oro_installer.yaml_persister.class:               Oro\Bundle\InstallerBundle\Persister\YamlPersister
    oro_installer.script_manager.class:               Oro\Bundle\InstallerBundle\ScriptManager
services:
    oro_installer.yaml_persister:
        class: '%oro_installer.yaml_persister.class%'
        arguments:
            - '%kernel.project_dir%/config'
            - '%kernel.environment%'

    kernel.listener.install.event:
        class: Oro\Bundle\InstallerBundle\EventListener\RequestListener
        arguments:
            - '%installed%'
            - '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 10 }

    oro_installer.script_manager:
        class: '%oro_installer.script_manager.class%'
        arguments:
            - '@kernel'

    oro_installer.namespace_migration:
        class: 'Oro\Bundle\InstallerBundle\CacheWarmer\NamespaceMigration'
        arguments:
            - '@doctrine'

    oro_installer.assets_install_command_listener:
        class: Oro\Bundle\InstallerBundle\EventListener\AssetsInstallCommandListener
        arguments:
            - '@filesystem'
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: console.command, method: beforeExecute }
            - { name: kernel.event_listener, event: console.terminate, method: afterExecute }
