security:
    firewalls:
        wsse_secured:
            pattern: ^/api/rest.*
            stateless:  true
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "UsernameToken"
            context: main
            logout_on_user_change: true
