services:
    Oro\Bundle\ReminderBundle\Command\SendRemindersCommand:
        public: false
        class: Oro\Bundle\ReminderBundle\Command\SendRemindersCommand
        tags:
            - { name: console.command }
