config:
    shim:
        'jquery.uniform':
            deps:
                - 'jquery'
        'jquery.select2':
            deps:
                - 'jquery'
            exports: 'Select2'
        'bootstrap-popover':
            deps:
                - 'jquery'
                - 'bootstrap-tooltip'
            exports: 'Popover'
        'jquery.datepair':
            deps:
                - 'jquery'
                - 'datepair'
        'jquery.multiselect':
            deps:
                - 'jquery-ui'
        'jquery.multiselect.filter':
            deps:
                - 'jquery.multiselect'
        'jquery.form':
            deps:
                - 'jquery'
        'json':
            exports: 'JSON'
        'bootstrap-util':
            deps:
                - 'jquery'
            exports: 'Util'
        'bootstrap-alert':
            deps:
                - 'jquery'
                - 'bootstrap-util'
        'bootstrap-dropdown':
            deps:
                - 'jquery'
                - 'popper'
                - 'bootstrap-util'
            exports: 'Dropdown'
        'bootstrap-modal':
            deps:
                - 'jquery'
                - 'bootstrap-util'
        'bootstrap-scrollspy':
            deps:
                - 'jquery'
                - 'bootstrap-util'
        'bootstrap-tab':
            deps:
                - 'jquery'
                - 'bootstrap-util'
        'bootstrap-tooltip':
            deps:
                - 'jquery'
                - 'popper'
                - 'bootstrap-util'
        'bootstrap-typeahead':
            deps:
                - 'jquery'
    map:
        '*':
            'jquery': 'oroui/js/extend/jquery'
            'jquery.select2': 'oroui/js/extend/select2'
            'jquery.multiselect': 'oroui/js/extend/jquery.multiselect'
            'jquery.multiselect.filter': 'oroui/js/extend/jquery.multiselect-filter'
            'chaplin': 'oroui/js/extend/chaplin'
            'underscore': 'oroui/js/extend/underscore'
            'backbone': 'oroui/js/extend/backbone'
            'bootstrap': 'oroui/blank/js/extend/bootstrap'
            'jquery-ui': 'oroui/js/jquery-ui-datepicker-l10n'
            'jquery.timepicker': 'oroui/js/extend/jquery.timepicker'
        'oroui/js/extend/jquery':
            'jquery': 'jquery'
        'oroui/js/extend/select2':
            'jquery.select2': 'jquery.select2'
        'oroui/js/select2-l10n':
            'jquery.select2': 'jquery.select2'
        'oroui/js/extend/jquery.multiselect':
            'jquery.multiselect': 'jquery.multiselect'
        'oroui/js/extend/jquery.multiselect-filter':
            'jquery.multiselect.filter': 'jquery.multiselect.filter'
        'oroui/js/extend/jquery-ui':
            'jquery-ui': 'jquery-ui'
        'oroui/js/extend/chaplin':
            'chaplin': 'chaplin'
        'oroui/js/extend/underscore':
            'underscore': 'underscore'
        'oroui/js/extend/backbone':
            'backbone': 'backbone'
        'oroui/blank/js/extend/bootstrap':
            'bootstrap': 'bootstrap'
        'oroui/js/jquery-ui-datepicker-l10n':
            'jquery-ui': 'oroui/js/extend/jquery-ui'
        'oroui/js/jquery-timepicker-l10n':
            'jquery.timepicker': 'jquery.timepicker'
        'oroui/js/extend/jquery.timepicker':
            'jquery.timepicker': 'jquery.timepicker'
        'chaplin':
            'backbone': 'backbone'
        'oroui/js/app/components/base/component':
            'backbone': 'backbone'
            'chaplin': 'chaplin'
        'oroui/js/mediator':
            'chaplin': 'chaplin'
        'oroui/js/tools':
            'chaplin': 'chaplin'
    paths:
        'text': 'bundles/bowerassets/text/text.js'
        'json': 'bundles/bowerassets/json2/json2.js'
        'base64': 'oroui/js/extend/base64.js'
        'jquery': 'bundles/components/jquery/jquery.js'
        'jquery-ui': 'bundles/oroui/lib/jquery-ui.js'
        'jquery.form': 'bundles/bowerassets/jquery-form/src/jquery.form.js'
        'jquery.mousewheel': 'bundles/bowerassets/jquery-mousewheel/jquery.mousewheel.js'
        'jquery.numeric': 'bundles/bowerassets/jquery.numeric/jquery.numeric.js'
        'jquery.uniform': 'bundles/npmassets/jquery.uniform/src/js/jquery.uniform.js'
        'jquery.select2': 'bundles/bowerassets/select2/select2.js'
        'jquery.multiselect': 'bundles/bowerassets/jquery-ui-multiselect-widget/src/jquery.multiselect.min.js'
        'jquery.multiselect.filter': 'bundles/bowerassets/jquery-ui-multiselect-widget/src/jquery.multiselect.filter.min.js'
        'jquery.cookie': 'bundles/bowerassets/jquery-cookie/jquery.cookie.js'
        'jquery.mCustomScrollbar': 'bundles/bowerassets/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js'
        'popper': 'oroui/js/extend/bootstrap/vendor/popper'
        'bootstrap-util': 'bundles/bowerassets/bootstrap/js/dist/util.js'
        'bootstrap-alert': 'bundles/bowerassets/bootstrap/js/dist/alert.js'
        'bootstrap-dropdown': 'bundles/bowerassets/bootstrap/js/dist/dropdown.js'
        'bootstrap-modal': 'bundles/bowerassets/bootstrap/js/dist/modal.js'
        'bootstrap-popover': 'bundles/bowerassets/bootstrap/js/dist/popover.js'
        'bootstrap-scrollspy': 'bundles/bowerassets/bootstrap/js/dist/scrollspy.js'
        'bootstrap-tab': 'bundles/bowerassets/bootstrap/js/dist/tab.js'
        'bootstrap-tooltip': 'bundles/bowerassets/bootstrap/js/dist/tooltip.js'
        'bootstrap-typeahead': 'bundles/oroui/lib/bootstrap/bootstrap-typeahead.js'
        'bootstrap': 'bundles/oroui/blank/lib/bootstrap.js'
        'underscore': 'bundles/bowerassets/underscore/underscore.js'
        'backbone': 'bundles/bowerassets/backbone/backbone.js'
        'chaplin': 'bundles/bowerassets/chaplin/chaplin.js'
        'jquery.timepicker': 'bundles/bowerassets/timepicker/jquery.timepicker.js'
        'jquery.datepair': 'bundles/bowerassets/datepair/dist/jquery.datepair.js'
        'datepair': 'bundles/bowerassets/datepair/dist/datepair.js'
        'cryptojs/core': 'bundles/bowerassets/crypto-js/core.js'
        'cryptojs/sha256': 'bundles/bowerassets/crypto-js/sha256.js'

        'ready': 'bundles/oroui/js/requirejs/ready.js'
        'tpl': 'bundles/oroui/js/requirejs/tpl.js'
        'oroui/blank/js/extend/bootstrap': 'bundles/oroui/blank/js/extend/bootstrap.js'
        'oroui/js/tools/api-accessor': 'bundles/oroui/js/tools/api-accessor.js'
        'oroui/js/app/ready-state-tracker': 'bundles/oroui/js/app/ready-state-tracker.js'
        'controllers/page-controller': 'bundles/oroui/js/app/controllers/page-controller.js'
        'oroui/js/app/modules/layout-module': 'bundles/oroui/js/app/modules/layout-module.js'
        'oroui/js/app/modules/messenger-module': 'bundles/oroui/js/app/modules/messenger-module.js'
        'oroui/js/app/modules/widgets-module': 'bundles/oroui/js/app/modules/widgets-module.js'
        'oroui/js/app/modules/input-widgets': 'bundles/oroui/js/app/modules/input-widgets.js'
        'oroui/js/app/modules/viewport-module': 'bundles/oroui/js/app/modules/viewport-module.js'
        'oroui/js/app/modules/ajax-error-module': 'bundles/oroui/js/app/modules/ajax-error-module.js'
        'oroui/js/app/modules/init-layout': 'bundles/oroui/js/app/modules/init-layout.js'
        'oroui/js/app/modules/component-shortcuts-module': 'bundles/oroui/js/app/modules/component-shortcuts-module.js'
        'oroui/js/app/application': 'bundles/oroui/js/app/application.js'
        'oroui/js/app/routes': 'bundles/oroui/js/app/routes.js'
        'oroui/js/app/models/base/collection': 'bundles/oroui/js/app/models/base/collection.js'
        'oroui/js/app/views/page/content-view': 'bundles/oroui/js/app/views/page/content-view.js'
        'oroui/js/app/views/page/messages-view': 'bundles/oroui/js/app/views/page/messages-view.js'
        'oroui/js/app/views/datepicker/datetimepicker-view': 'bundles/oroui/js/app/views/datepicker/datetimepicker-view.js'
        'oroui/js/app/views/datepicker/datepicker-view': 'bundles/oroui/js/app/views/datepicker/datepicker-view.js'
        'oroui/js/app/views/tab-collection-view': 'bundles/oroui/js/app/views/tab-collection-view.js'
        'oroui/js/app/views/flash-message-view': 'bundles/oroui/js/app/views/flash-message-view.js'
        'oroui/js/app/views/swipeable-view': 'bundles/oroui/js/app/views/swipeable-view.js'

        'oroui/js/viewport-manager': 'bundles/oroui/js/viewport-manager.js'
        'oroui/js/delete-confirmation': 'bundles/oroui/js/delete-confirmation.js'
        'oroui/js/standart-confirmation': 'bundles/oroui/js/standart-confirmation.js'
        'oroui/js/error': 'bundles/oroui/js/error.js'
        'oroui/js/layout': 'bundles/oroui/js/layout.js'
        'oroui/js/mediator': 'bundles/oroui/js/mediator.js'
        'oroui/js/tools': 'bundles/oroui/js/tools.js'
        'oroui/js/messenger': 'bundles/oroui/js/messenger.js'
        'oroui/js/modal': 'bundles/oroui/js/modal.js'

        'oroui/js/extend/jquery': 'bundles/oroui/js/extend/jquery.js'
        'oroui/js/extend/underscore': 'bundles/oroui/js/extend/underscore.js'

        'oroui/js/app/components/app-loading-mask-component': 'bundles/oroui/js/app/components/app-loading-mask-component.js'
        'oroui/js/app/components/app-loading-bar-component': 'bundles/oroui/js/app/components/app-loading-bar-component.js'
        'oroui/js/app/components/ajax-button': 'bundles/oroui/js/app/components/ajax-button.js'
        'oroui/js/app/components/jquery-widget-component': 'bundles/oroui/js/app/components/jquery-widget-component.js'
        'oroui/js/app/components/tabs-component': 'bundles/oroui/js/app/components/tabs-component.js'
        'oroui/js/app/components/view-component': 'bundles/oroui/js/app/components/view-component.js'
        'oroui/js/app/components/viewport-component': 'bundles/oroui/js/app/components/viewport-component.js'
        'oroui/js/app/components/widget-component': 'bundles/oroui/js/app/components/widget-component.js'
        'oroui/js/app/components/widget-form-component': 'bundles/oroui/js/app/components/widget-form-component.js'
        'oroui/js/app/components/widget-picker-component': 'bundles/oroui/js/app/components/widget-picker-component.js'
        'oroui/js/app/components/element-value-copy-to-clipboard-component': 'bundles/oroui/js/app/components/element-value-copy-to-clipboard-component.js'
        'oroui/js/widget-manager': 'bundles/oroui/js/widget/widget-manager.js'
        'oroui/js/widget/abstract-widget': 'bundles/oroui/js/widget/abstract-widget.js'
        'oroui/js/widget/collapse-widget': 'bundles/oroui/js/widget/collapse-widget.js'
        'oroui/js/widget/collapse-group-widget': 'bundles/oroui/js/widget/collapse-group-widget.js'
        'oro/block-widget': 'bundles/oroui/js/widget/block-widget.js'

        'oroui/js/input-widget-manager': 'bundles/oroui/js/input-widget-manager.js'
        'oroui/js/app/views/input-widget/abstract': 'bundles/oroui/js/app/views/input-widget/abstract.js'
        'oroui/js/app/views/input-widget/uniform-file': 'bundles/oroui/js/app/views/input-widget/uniform-file.js'
        'oroui/js/app/views/input-widget/uniform-select': 'bundles/oroui/js/app/views/input-widget/uniform-select.js'
        'oroui/js/app/views/input-widget/select2': 'bundles/oroui/js/app/views/input-widget/select2.js'

        'oroui/js/content-processor/pinned-dropdown-button': 'oroui/js/content-processor/pinned-dropdown-button.js'

        'oroui/js/extend/polyfill': 'oroui/js/extend/polyfill'

        'oroui/js/app/views/loading-bar-view': 'bundles/oroui/js/app/views/loading-bar-view.js'

        'oroui/js/app/views/layout-subtree-view': 'bundles/oroui/js/app/views/layout-subtree-view.js'
        'oroui/js/layout-subtree-manager': 'bundles/oroui/js/layout-subtree-manager.js'

    appmodules:
        - oroui/js/app/modules/init-layout
        - oroui/js/app/modules/layout-module
        - oroui/js/app/modules/messenger-module
        - oroui/js/app/modules/widgets-module
        - oroui/js/app/modules/ajax-error-module
        - oroui/js/app/modules/input-widgets
        - oroui/js/app/modules/component-shortcuts-module
        - oroui/js/app/modules/viewport-module

build:
    paths:
#       jQuery.UI after v.1.11.2 started to support AMD. And that broke a js-build with
#       files which does not support AMD. jquery.multiselect and jquery.multiselect.filter
#       use AMD without dependency, therefore it's excluded
        'jquery.multiselect': 'empty:'
        'jquery.multiselect.filter': 'empty:'
#        Transpiled bootstrap modules don't support AMD, but requires Popper from global scope
#        and it is actually in AMD module
        'bootstrap-dropdown': 'empty:'
        'bootstrap-tooltip': 'empty:'
        'bootstrap-popover': 'empty:'
