security:
    firewalls:
        embedded_form:
            pattern:   ^/embedded-form/(submit|success)
            provider:  chain_provider
            anonymous: true
            logout_on_user_change: true
