config:
    paths:
        'orosidebar/js/sidebar-constants': 'orosidebar/js/sidebar-constants'

        'orosidebar/js/app/models/sidebar-model': 'bundles/orosidebar/js/app/models/sidebar-model.js'
        'orosidebar/js/app/views/sidebar-view': 'bundles/orosidebar/js/app/views/sidebar-view.js'

        'orosidebar/js/app/models/sidebar-widget-container-model': 'bundles/orosidebar/js/app/models/sidebar-widget-container-model.js'
        'orosidebar/js/app/models/sidebar-widget-container-collection': 'bundles/orosidebar/js/app/models/sidebar-widget-container-collection.js'
        'orosidebar/js/app/views/sidebar-widget-container/widget-container-view': 'bundles/orosidebar/js/app/views/sidebar-widget-container/widget-container-view.js'
        'orosidebar/js/app/views/sidebar-widget-container/widget-container-icon-view': 'bundles/orosidebar/js/app/views/sidebar-widget-container/widget-container-icon-view.js'
        'orosidebar/js/app/views/widget-picker-modal-view': 'bundles/orosidebar/js/app/views/widget-picker-modal-view.js'
        'orosidebar/js/app/views/widget-setup-modal-view': 'bundles/orosidebar/js/app/views/widget-setup-modal-view.js'

        'orosidebar/widget/sticky-note': 'bundles/orosidebar/sidebar_widgets/sticky_note/js/widget.js'

        'orosidebar/js/app/components/sidebar-component': 'bundles/orosidebar/js/app/components/sidebar-component.js'
