parameters:
    oro_ui.content_provider.current_route.class:   Oro\Bundle\UIBundle\ContentProvider\CurrentRouteContentProvider
    oro_ui.content_provider.flash_messages.class:  Oro\Bundle\UIBundle\ContentProvider\FlashMessagesContentProvider

services:
    oro_ui.content_provider.current_route:
        class: '%oro_ui.content_provider.current_route.class%'
        arguments:
            - '@request_stack'
        tags:
            - { name: oro_ui.content_provider }

    oro_ui.content_provider.flash_messages:
        class: '%oro_ui.content_provider.flash_messages.class%'
        arguments:
            - '@session'
        tags:
            - { name: oro_ui.content_provider }
