knp_gaufrette:
    adapters:
        importexport:
            local:
                directory: '%kernel.project_dir%/var/%oro_importexport.importexport_dir%'
    filesystems:
        importexport:
            adapter:    importexport
            alias:      importexport_filesystem
