services:
    Oro\Bundle\LayoutBundle\Command\AssetsThemeDumpCommand:
        public: false
        class: Oro\Bundle\LayoutBundle\Command\AssetsThemeDumpCommand
        tags:
            - { name: console.command }

    Oro\Bundle\LayoutBundle\Command\DebugCommand:
        public: false
        class: Oro\Bundle\LayoutBundle\Command\DebugCommand
        tags:
            - { name: console.command }
